Update to-do.yaml

diff --git a/.github/workflows/to-do.yaml b/.github/workflows/to-do.yaml
--- a/.github/workflows/to-do.yaml
+++ b/.github/workflows/to-do.yaml
@@ -42,9 +42,26 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY}}
           script: |
-            cd /home/ubuntu/to-do-app || git clone https://github.com/alishasaiyed7/to-do-app /home/ubuntu/to-do-app
+            cd /home/ubuntu/prj6-ToDo app on nodejs and automate || git clone https://github.com/alishasaiyed7/to-do-app /home/ubuntu/prj6-ToDo app on nodejs and automate
             cd to-do-app
             git pull origin main
             npm install
-            npm install -g pm2
-            pm2 restart app || pm2 start app.js --name "to-do-app"
+            # Check if PM2 is installed, if not install
+            if ! command -v pm2 &> /dev/null
+            then
+               echo "⚙️ PM2 not found. Installing..."
+               sudo npm install -g pm2
+            else
+               echo "✅ PM2 already installed"
+            fi
+
+    
+            if pm2 list | grep -q "todo-app"
+            then
+              echo "🔄 Restarting existing PM2 process..."
+              pm2 restart todo-app
+            else
+              echo "🚀 Starting new PM2 process..."
+              pm2 start app.js --name todo-app
+            fi
+            pm2 save
